version: 2.1
orbs:
  heroku: circleci/heroku@1.0.1
jobs:
  build:
    docker:
      - image: 'circleci/python:latest'
    steps:
      - checkout
      - run: echo 'hello world'
      - heroku/deploy-via-git
